
name: Complex  # Name of Workflow

on: push  # Triggering Event

jobs:  # Add Jobs
  ubuntu:  # name of first Job
    runs-on: ubuntu-latest  # specify a system for runner 
    steps:  # job step
    - run: date  # command of the step (- run) [print date]
  windows:  # name of second Job
    runs-on: window-latest  # specify a system for runner 
    steps:  # job step
    - run: date  # command of the step (- run)
  macos:  # name of third Job
    runs-on: macos-latest  # specify a system for runner  
    steps:  # job step
    - run: date  # command of the step (- run)
  depends:   # name of fourth Job
    needs: [ubuntu, windows, macos]
    runs-on: macos-latest  # specify a system for runner  
    steps:  # job step
    - run: date  # command of the step (- run)
  
  
  
